# check.py
# CSE-GO Pipeline — Step 3: Adversarial Verification
#
# What this file does:
#   Reads a batch JSON file generated by generate.py.
#   For each question, makes a second Claude API call that acts as a
#   "hostile examiner" — checking whether the question is actually
#   grounded in its cited extract, the answer is unambiguous, and the
#   distractors are factually clean.
#   Updates each record's status to "pass" or "flag" and saves back to disk.
#
# ── HOW TO RUN ────────────────────────────────────────────────────────────────
#
#   # Check the most recent batch file:
#   python check.py
#
#   # Or specify a file explicitly:
#   python check.py questions/batch_20260422_150915.json
#
# ─────────────────────────────────────────────────────────────────────────────

import os
import sys
import json
import glob
import anthropic


# ── CONFIGURATION ─────────────────────────────────────────────────────────────

QUESTIONS_DIR = "./questions"
CLAUDE_MODEL  = "claude-sonnet-4-6"

# ── CHECKER PROMPT ────────────────────────────────────────────────────────────
# This prompt asks Claude to play devil's advocate against generate.py's output.
# It checks three things:
#   1. Grounding — does the cited_extract actually prove the correct answer?
#   2. Ambiguity — could another option also be argued correct from the extract?
#   3. Distractor cleanliness — are wrong options factually false (not just unlisted)?

CHECKER_SYSTEM = """\
You are a strict quality-control examiner for UPSC Civil Services Examination questions.
Your job is to find flaws in MCQ questions that another AI has generated.

You will receive:
  - A question with four options (A/B/C/D)
  - The claimed correct answer
  - The cited_extract: the exact sentence(s) from the source that supposedly prove the answer

You must check THREE things and output ONLY valid JSON — no preamble, no markdown fences:

1. GROUNDING: Does the cited_extract directly and explicitly state the fact that makes the correct answer right?
   FAIL if: the extract only implies it, requires inference, or does not mention the key fact at all.

2. AMBIGUITY: Based on the cited_extract alone (no outside knowledge), is the correct answer the ONLY defensible choice?
   FAIL if: another option could reasonably be chosen using only the extract.

3. DISTRACTOR CLEANLINESS: Are the wrong options clearly wrong based on the extract?
   FAIL if: a distractor contains a factual claim that the extract does not contradict,
   making it look plausible in a way that could confuse a well-prepared student.

Output format — exactly these keys:
{
  "verdict":      "pass" or "flag",
  "grounding_ok": true or false,
  "ambiguity_ok": true or false,
  "distractors_ok": true or false,
  "flag_reason":  "One clear sentence explaining the primary problem, or null if verdict is pass."
}\
"""

CHECKER_USER_TEMPLATE = """\
QUESTION:
{question}

OPTIONS:
A) {opt_A}
B) {opt_B}
C) {opt_C}
D) {opt_D}

CLAIMED CORRECT ANSWER: {correct}

CITED EXTRACT (verbatim from source):
\"{cited_extract}\"

Check this question against the three criteria and return your JSON verdict.\
"""

# ─────────────────────────────────────────────────────────────────────────────


def find_latest_batch(questions_dir):
    """Returns the path to the most recently modified batch JSON file."""
    pattern = os.path.join(questions_dir, "batch_*.json")
    files   = glob.glob(pattern)
    if not files:
        return None
    return max(files, key=os.path.getmtime)


def check_one_question(client, record):
    """
    Calls Claude to adversarially verify a single question record.
    Returns the updated record with status and flag_reason filled in.
    """
    options = record.get("options") or {}

    user_message = CHECKER_USER_TEMPLATE.format(
        question       = record.get("question", ""),
        opt_A          = options.get("A", ""),
        opt_B          = options.get("B", ""),
        opt_C          = options.get("C", ""),
        opt_D          = options.get("D", ""),
        correct        = record.get("correct_answer", ""),
        cited_extract  = record.get("cited_extract", "")
    )

    response = client.messages.create(
        model      = CLAUDE_MODEL,
        max_tokens = 512,
        system     = [
            {
                "type": "text",
                "text": CHECKER_SYSTEM,
                "cache_control": {"type": "ephemeral"}
            }
        ],
        messages   = [{"role": "user", "content": user_message}]
    )

    raw = response.content[0].text.strip()

    try:
        result = json.loads(raw)
    except json.JSONDecodeError:
        cleaned = raw.removeprefix("```json").removeprefix("```").removesuffix("```").strip()
        try:
            result = json.loads(cleaned)
        except json.JSONDecodeError:
            result = {
                "verdict":        "flag",
                "grounding_ok":   None,
                "ambiguity_ok":   None,
                "distractors_ok": None,
                "flag_reason":    "check.py could not parse Claude's response — manual review needed."
            }

    record["status"]          = result.get("verdict", "flag")
    record["grounding_ok"]    = result.get("grounding_ok")
    record["ambiguity_ok"]    = result.get("ambiguity_ok")
    record["distractors_ok"]  = result.get("distractors_ok")
    record["flag_reason"]     = result.get("flag_reason")

    return record


def print_result(record, index):
    verdict = record.get("status", "unknown").upper()
    marker  = "✓ PASS" if verdict == "PASS" else "✗ FLAG"
    print(f"\n  Q{index+1}. {marker}  [{record['source']['filename']}  p.{record['source']['page']}]")
    print(f"       {record.get('question', '')[:90]}{'…' if len(record.get('question','')) > 90 else ''}")
    if record.get("flag_reason"):
        print(f"       Reason: {record['flag_reason']}")
    checks = []
    for key, label in [("grounding_ok","Grounding"), ("ambiguity_ok","Unambiguous"), ("distractors_ok","Distractors")]:
        val = record.get(key)
        if val is not None:
            checks.append(f"{label}:{'✓' if val else '✗'}")
    if checks:
        print(f"       {' | '.join(checks)}")


def main():
    # ── 1. Find the batch file to check ──────────────────────────────────────
    if len(sys.argv) > 1:
        filepath = sys.argv[1]
    else:
        filepath = find_latest_batch(QUESTIONS_DIR)

    if not filepath or not os.path.exists(filepath):
        print(f"\nERROR: No batch file found in '{QUESTIONS_DIR}'.")
        print("Run generate.py first, then run check.py.")
        sys.exit(1)

    print(f"\nChecking: {filepath}")

    # ── 2. Load records ───────────────────────────────────────────────────────
    with open(filepath, "r", encoding="utf-8") as f:
        records = json.load(f)

    # Only check questions not yet checked (status == "pending_check")
    # Re-running check.py on an already-checked file is safe — it skips done ones
    to_check = [r for r in records if r.get("status") == "pending_check"]
    already  = len(records) - len(to_check)

    if already > 0:
        print(f"  {already} question(s) already checked — skipping.")
    if not to_check:
        print("  Nothing to check. All questions have been verified.")
        sys.exit(0)

    print(f"  {len(to_check)} question(s) to verify ...\n")

    # ── 3. Check API key ──────────────────────────────────────────────────────
    if not os.environ.get("ANTHROPIC_API_KEY"):
        print("\nERROR: ANTHROPIC_API_KEY environment variable not set.")
        print("Run:  export ANTHROPIC_API_KEY='sk-ant-...'")
        sys.exit(1)

    client = anthropic.Anthropic()

    # ── 4. Check each question ────────────────────────────────────────────────
    print(f"  {'─'*56}")

    for i, record in enumerate(records):
        if record.get("status") != "pending_check":
            continue

        # Skip questions that already had a parse error in generate.py
        if record.get("parse_error"):
            record["status"]      = "flag"
            record["flag_reason"] = "generate.py parse error — question was never properly formed."
            print_result(record, i)
            continue

        print(f"  [{i+1}/{len(records)}] Checking ...", end="", flush=True)
        record = check_one_question(client, record)
        print(f"\r", end="")
        print_result(record, i)

    # ── 5. Save updated records back to the same file ─────────────────────────
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(records, f, indent=2, ensure_ascii=False)

    # ── 6. Summary ────────────────────────────────────────────────────────────
    passed = sum(1 for r in records if r.get("status") == "pass")
    flagged = sum(1 for r in records if r.get("status") == "flag")

    print(f"\n{'═'*52}")
    print(f"  CHECK COMPLETE")
    print(f"  Total questions      : {len(records)}")
    print(f"  Passed               : {passed}")
    print(f"  Flagged              : {flagged}")
    print(f"  Updated file         : {filepath}")
    print(f"{'═'*52}")
    print("\nNext step → run review.py to inspect flagged questions.")


if __name__ == "__main__":
    main()
